# https://github.com/flxn/qrcode2stl
services:
  app:
    build: ./
    container_name: qrcode2stl
    restart: on-failure:5
    ports:
      - 8082:8080
    security_opt:
      - apparmor:docker-default
      - no-new-privileges
    read_only: true
